version: '2.3'
services:
  app-backend:
    image: openjdk:11-jdk
    command:
      - "api/run"
    entrypoint: java
    command:
      - "-jar"
      - "api-doc-api-assembly.jar"
    environment:
      - AWS_PROFILE
      - ENVIRONMENT=development
    ports:
      - "8080:8080"
    volumes:
      - ./app-backend/:/opt/api-doc/app-backend/
      - $HOME/.sbt:/root/.sbt
      - $HOME/.coursier:/root/.coursier
      - ./.bintray:/root/.bintray
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.aws:/root/.aws:ro
    working_dir: /opt/api-doc/app-backend/api/target/scala-2.12/
